import Axios from 'axios'
import NavAdmin from '@/components/NavAdmin'
import PatientAction from '@/components/PatientAction'  // Ajuste o nome do componente de ação
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import MenuUsers from '@/components/MenuUsers'

export default function pacientes() {

  const API_URL = "http://localhost:8080/api/pacientes"  // URL de pacientes
  
  const [pacientes, setPacientes] = useState([]); 
  
  useEffect(() => {
    const getAllPacientes = async () => {
      try {
        const response = await Axios.get(API_URL);
        setPacientes(response.data);
        console.log(response.data);
      } catch (error) {
        console.error('Erro ao buscar os pacientes:', error);
      }
    };

    getAllPacientes();

  }, []);

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuUsers />
      </div>

      <div className="d-flex justify-content-center p-4" style={{ background: 'linear-gradient(45deg, #ffffff, #d4edda)' }}>
        <div className="container">
        <div className="row mb-4 pb-3" style={{ borderBottom: '1px solid #a0a0a0' }}>
          <h3 className="text-success">Lista de Pacientes</h3>
        </div>

          <div className="d-flex justify-content-center mb-4">
            <Link className="nav-link" href="/admin/pacientes/create">
              <button className="btn btn-success btn-lg p-3">Cadastrar</button>
            </Link>
          </div>

          <div className="row">
            {pacientes.map(paciente => (
              <div key={paciente.idPacientes} className="col-md-4 mb-4" id={`paciente-${paciente.idPacientes}`}>
                <div className="card shadow-lg border-success">
                  <div className="card-body">
                    <h5 className="card-title text-success">{paciente.primeiroNome} {paciente.ultimoNome}</h5>
                    <p className="card-text"><strong>Observações:</strong> {paciente.observacoes || 'N/A'}</p>
                    <p className="card-text"><strong>Condição:</strong> {paciente.condicao}</p>
                    <p className="card-text"><strong>Pedagogo:</strong> {paciente.profNome} {paciente.profSobrenome}</p>
                    <p className="card-text"><strong>Endereço:</strong> {paciente.logradouro}, {paciente.numero}</p>
                    <p className="card-text"><strong>Complemento:</strong> {paciente.complemento || 'N/A'}</p>
                    <p className="card-text"><strong>Numero:</strong> {paciente.numero}</p>
                    <p className="card-text"><strong>Bairro:</strong> {paciente.bairro}</p>
                    <p className="card-text"><strong>Cidade:</strong> {paciente.cidade}</p>
                    <p className="card-text"><strong>Estado:</strong> {paciente.estado}</p>
                    <div className="d-flex justify-content-end">
                      <PatientAction pid={paciente.idPacientes} />
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </>
  );
}