import Axios from 'axios'
import NavAdmin from '@/components/NavAdmin'
import ConditionAction from '@/components/ConditionAction'  // Ajuste o nome do componente de ação
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import MenuUsers from '@/components/MenuUsers'

export default function idProfissoes() {

  const API_URL = "http://localhost:8080/api/condicoes"  // URL de profissionais
  
  const [condicoes, setCondicoes] = useState([]); 
  
  useEffect(() => {
    const getAllCondicoes = async () => {
      try {
        const response = await Axios.get(API_URL);
        setCondicoes(response.data);
        console.log(response.data);
      } catch (error) {
        console.error('Erro ao buscar as condicoes:', error);
      }
    };

    getAllCondicoes();

  }, []);

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuUsers />
      </div>
  
      <div className="d-flex justify-content-center p-4" style={{ background: 'linear-gradient(45deg, #ffffff, #d4edda)', minHeight: '100vh'}}>
        <div className="container">
          <div className="row mb-4 pb-3" style={{ borderBottom: '1px solid #a0a0a0' }}>
            <h3 className="text-success">Lista de Condicoes</h3>
          </div>
  
          <div className="d-flex justify-content-center mb-4">
            <Link className="nav-link" href="/admin/condicoes/create">
              <button className="btn btn-success btn-lg p-3">Cadastrar</button>
            </Link>
          </div>
  
          <div className="row">
            {condicoes.map(condicao => (
              <div key={condicao.id} className="col-md-4 mb-4" id={`condicao-${condicao.id}`}>
                <div className="card shadow-lg border-success">
                  <div className="card-body">
                    <h5 className="card-title text-success">{condicao.nome}</h5>
                    <p className="card-text"><strong>Descrição: </strong> {condicao.descricao}</p>
                    <div className="d-flex justify-content-end">
                      <ConditionAction pid={condicao.id} />
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </>
  );  
}
